filter:
    paths:
        - "**/*"  # Inkludera alla filer

tools:
    javascript_coverage: true
    eslint:
        config:
            extends: "react-app" # Använder ESLint-konfigurationen som skapades av Create React App
    sql_lint:
        enabled: true  # Aktivera SQL-lint
    sql_query_analyzer:
        enabled: true  # Aktivera SQL-query-analysatorn

build:
    coverage:
        file: coverage/lcov.info  # ange rätt täckningsrapportfil
        format: lcov  # Ange formatet för täckningsrapporten
    environment:
        node:
            version: "18"  # Node.js
    branches:
        only: all # Pushar på alla grenar
        
checks:
    javascript: 
        code_rating: true
        unused_variables: true
        no_console: true
        complexity: true  # Kontrollera kodkomplexitet
    sql:
        sql_injection: true  # SQL-injection analys
        unused_queries: true  # Identifiera oanvända SQL-frågor

# Testkonfiguration
tests:
    override:
        - "npm install"
        - "npm test"

# Aktivera kodkvalitetsbetyg (code rating)
code_quality:
    enabled: true

