build:
    environment:
        node:
            version: "18"
    dependencies:
        override:
            - npm install --production  # Installerar endast produktionsberoenden för snabbare körning

tools:
    eslint:
        enabled: true  # Endast ESLint används för kodanalys, inget extra

filter:
    paths:
        - src/  # Analyserar endast src/
    excluded_paths:
        - "**/*"  # Ignorerar ALLA andra filer utanför src/ för att minimera analysen

checks:
    javascript:
        code_rating: true  # Kodbetyg
        unused_variables: true  # Analysera oanvända variabler
