tools:
    eslint:
        config:
            extends: "react-app" # Anv채nder ESLint-konfigurationen som skapades av Create React App
    sql_lint:
        enabled: true
    sql_query_analyzer:
        enabled: true

build:
    environment:
        node:
            version: "18"  # Node.js
    branches:
        only: all # Pushar p책 alla grenar
filter:
    paths:
        - "src/*"  # React-kod i 'src/'
        - "backend/*"  # Backend-kod i en separat mapp

checks:
    javascript: 
        code_rating: true
        unused_variables: true
        no_console: true
        complexity: true  # Kontrollera kodkomplexitet
    sql:
        sql_injection: true  # SQL-injection analys
        unused_queries: true  # Identifiera oanv채nda SQL-fr책gor

# Testkonfiguration
tests:
    override:
        - "npm install"
        - "npm test"

# Aktivera kodkvalitetsbetyg (code rating)
code_quality:
    enabled: true

