build:
    environment:
        node:
            version: "18"  # Ange rätt Node.js-version
    dependencies:
        override:
            - npm install  # Installerar beroenden
    tests:
        override:
            - npm test || echo "Inga tester hittades"  # Kör dina tester

tools:
    javascript_analyzer:
        enabled: true
    eslint:
        enabled: true  # Använd ESLint för kodanalys

filter:
    paths:
        - src/
        - tests/
    excluded_paths:
        - node_modules/**
        - logs/**
        - dist/**
        - vendor/**

checks:
    javascript:
        code_rating: true
        complexity: true
        unused_variables: true
        no_console: true
