build:
    timeout: 300  # Timeout på 5 minuter (300 sekunder)
    environment:
        node:
            version: "18"
    dependencies:
        override:
            - npm install --production  # Installerar endast produktionsberoenden för snabbare körning

tools:
    eslint:
        enabled: true  # Endast ESLint används för kodanalys, inget extra

filter:
    paths:
        - src/  # Analyserar endast src/
    excluded_paths:
        - node_modules/**
        - logs/**
        - dist/**
        - vendor/**  # Ignorerar stora, onödiga mappar, men behåller src/

checks:
    javascript:
        code_rating: true  # Kodbetyg
        unused_variables: true  # Analysera oanvända variabler
