build:
    environment:
        node:
            version: "18"  # Ange rätt Node.js-version
    dependencies:
        override:
            - npm install  # Installerar beroenden
    tests:
        override:
            - npm test      # Kör dina tester

tools:
    eslint:
        config:
            extends: "eslint:recommended"  # ESLint-konfiguration
    javascript_coverage: true  # Analyserar kodtäckning
    sql_lint:
        enabled: true           # Aktiverar SQL-lint
    sql_query_analyzer:
        enabled: true           # Analyserar SQL-frågor

filter:
    paths:
        - "**/*"  # Inkludera alla filer i analysen

checks:
    javascript:
        code_rating: true
        complexity: true
        unused_variables: true
        no_console: true

    sql:
        sql_injection: true  # Kontrollera mot SQL-injection
        unused_queries: true