name: CI/CD Pipeline

on:
  push:
    branches:
      - '**' # Pushar på alla grenar
  pull_request:
    branches:
      - '**' # Pull request på alla grenar

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Set up environment variables
      - name: Set up environment variables
        run: | 
          echo "API_KEY=${{ secrets.API_KEY }}" >> .env
          echo "JWT_KEY=${{ secrets.JWT_KEY }}" >> .env

      # 5. Run tests
      - name: Run tests
        run: npm test

      # 6. Lint code
      - name: Run ESLint
        run: npx eslint .

      # 7. Upload coverage report (optional)
      - name: Upload test coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage/